yarnPath: ".yarn/releases/yarn-berry.cjs"

enableGlobalCache: true

enableTransparentWorkspaces: false # 必须通过workspace协议安装依赖

nodeLinker: node-modules # 不从pnp的zip中取依赖

npmRegistryServer: "https://registry.npm.taobao.org" # npm源
